/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A message extracted from source code */
export interface ExtractedMessage {
  id: string
  message?: string
  context?: string
  comment?: string
  placeholders: Record<string, string>
  origin?: Origin
}

/** Result of message extraction containing messages and any warnings */
export interface ExtractionResult {
  messages: Array<ExtractedMessage>
  warnings: Array<string>
}

/** Represents the location where a message was found */
export interface Origin {
  filename: string
  line: number
  column?: number
}
/**
 * Extract messages from source code
 *
 * This function parses JavaScript/TypeScript code and extracts internationalization
 * messages from lingui macro calls and components.
 *
 * # Arguments
 *
 * * `source_code` - The source code to analyze
 * * `filename` - The filename (used for error reporting and source maps)
 *
 * # Returns
 *
 * A Promise that resolves to an ExtractionResult containing:
 * * `messages` - Array of extracted messages
 * * `warnings` - Array of warning messages encountered during extraction
 *
 * # Example
 *
 * ```javascript
 * const result = await extractMessages(sourceCode, 'app.tsx');
 * console.log(result.messages);
 * ```
 */
export declare function extractMessages(sourceCode: string, filename: string): Promise<ExtractionResult>
