name: CI - Native Tools

on:
  push:
    branches:
      - main
      - next
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/*.md"
      - LICENSE
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/build-native-tools.yml
