name: Release

on:
  release:
    types: [ released, prereleased ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: 'wasm32-wasip1'

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install npm CLI
        run: npm install -g npm@latest

      - name: Build and publish 'latest' tag
        working-directory: packages/lingui-macro
        if: ${{ github.event.action == 'released' }}
        run: npm publish

      - name: Build and publish 'next' tag
        working-directory: packages/lingui-macro
        if: ${{ github.event.action == 'prereleased' }}
        run: npm publish --tag next
